name: Continuous Integration
on: [push]
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build:
        - llvm
        - gcc
        include:
        - build: llvm
          setup: |
            sudo add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main' && \
            sudo apt-get update && \
            sudo apt-get install clang-9
          cxx: clang++-9
        - build: gcc
          setup: |
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test && \
            sudo apt-get update && \
            sudo apt-get install g++-9
          cxx: g++-9
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install toolchain
      run: ${{ matrix.setup }}
    - name: Build
      run: CXX=${{ matrix.cxx }} make -C test
    - name: Test
      run: test/test
  macos:
    name: macOS
    runs-on: macOS-10.14
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Build
      run: make -C test
    - name: Test
      run: test/test
