name: Documentation
on: [push]
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install toolchain
      run: sudo apt-get install doxygen && pip3 install Sphinx breathe sphinx-rtd-theme
    - name: Build
      run: PATH=$PATH:/usr/local/bin make -C doc
