name: Documentation
on: [push]
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install toolchain
      run: sudo apt-get install doxygen && pip3 install -U Sphinx breathe sphinx-rtd-theme
    - name: Build
      run: make -C doc && touch ./doc/build/.nojekyll
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.3.1
      env:
        PERSONAL_TOKEN: ${{ secrets.PAT }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./doc/build
