name: Documentation
on: [push]
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install toolchain
      run: sudo apt-get install doxygen python3-sphinx python3-breathe python3-sphinx-rtd-theme
    - name: Build
      run: make -C doc
